### ISSUE TITLE
General issue with course materials and Azure Notebooks

### ISSUE THREAD

**Issue by hanovec** [MicrosoftLearning/Principles-of-Machine-Learning-R#10]
Unable to load some libraries into Azure notebook. Seems to me that all courses from Data Science track should use same environment for running notebooks and preferable it should be Microsoft environment if courses are about Microsoft technologies.

**Comment by StephenElston** [comment]
Very sorry you are having these problems with running certain R packages in Azure Notebooks. We are working to resolve this problem.
