### ISSUE TITLE
Broken creation of the test set in Module1

### ISSUE THREAD

**Issue by mormegil-cz** [MicrosoftLearning/Principles-of-Machine-Learning-R#8]
I have no idea if it is my local problem or what, but when trying the Module1 notebook, the test set was created incorrectly, so that it contained only _virginica_ samples (I noticed it by the very strange-looking graphs at the bottom).

AFAICT, the construction of the test set using `rownames` evaluates the rownames of the already sampled `train.iris`, which are obviously just 1–105, and by removing those from the original set, just the sequentially last 45 samples remain, i.e. most of the _virginicas_.

I fixed the problem by replacing the test set construction with
`test.iris = setdiff(iris, train.iris)`
which throws a few join warnings, but seems to work better.

**Comment by StephenElston** [comment]
Sorry you have had difficulty. Glad you found a work-around. 

I have tested the notebook, both locally and in Azure Notebooks, and cannot reproduce the problem.
