### ISSUE TITLE
Visualisation for Regression modul issue

### ISSUE THREAD

**Issue by hanovec** [MicrosoftLearning/Principles-of-Machine-Learning-R#9]
Using Azure notebooks there are following issues (setup.ipynb was run first as mentioned in course)

- hexbin plot is empty
- error in last part of module (multi-axis views) - Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]): there is no package called ‘stringr’

**Comment by StephenElston** [comment]
We have recommended that you use a local environment for these R labs. There are several problems that have arisen in the Azure Notebooks environment.
